# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js Backend Deployment

on:
  workflow_dispatch: # Allows manual triggering of the workflow
    inputs:
      branch:
        description: "The branch to deploy"
        required: false
        default: "main"

jobs:
  deploy:
    name: Deploy Backend to Vercel
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install backend dependencies
        run: npm ci
        working-directory: ./server

      - name: Run backend tests
        run: npm test --passWithNoTests
        working-directory: ./server

      - name: Start backend server (optional)
        run: npm run build
        working-directory: ./server

      - name: Start backend server (optional)
        run: npm run start
        working-directory: ./server

      - name: Deploy to Vercel
        run: npx vercel --prod --token=$VERCEL_TOKEN --yes
        working-directory: ./server
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}